spring.application.name = N_plus_one_query

# MySQL config
spring.datasource.driver-class-name = com.mysql.cj.jdbc.Driver
spring.datasource.url = jdbc:mysql://localhost:3306/n_plus_query?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username = root
spring.datasource.password = admin

spring.jackson.time-zone = Asia/Ho_Chi_Minh
spring.jpa.properties.hibernate.jdbc.time_zone = Asia/Ho_Chi_Minh

#spring.jpa.hibernate.ddl-auto = none
#spring.jpa.hibernate.ddl-auto = create
spring.jpa.hibernate.ddl-auto = update
#spring.jpa.hibernate.ddl-auto = create-drop

spring.jpa.show-sql = true
spring.jpa.properties.hibernate.format_sql = true


# swagger-ui: http://localhost:8080/swagger-ui/index.html